name: Build
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Download JI jar
        run: wget https://repo1.maven.org/maven2/net/imagej/ij/1.53c/ij-1.53c.jar
      - name: Build the plugin
        run: javac -cp ./ij-1.*.jar Plugin_Wykrywania.java
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: IJ Plugin
          path: ./Plugin_Wykrywania*.class
          retention-days: 32
